# Generated by Django 2.2 on 2019-04-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_main_branch_name',
            field=models.CharField(default='main', max_length=20),
        ),
    ]
