# Generated by Django 2.2 on 2019-04-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_blood_bank_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_seek',
            name='bank_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='donor_reports',
            name='bank_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
